### ISSUE TITLE
move code to slides/solution

### ISSUE THREAD

**Issue by chitopunk** [wizelineacademy/terraform-academy#23]
* We need to move the code from lesson0x/* to slides/lesson0x/solution
* Point PITCH md file to the new location
* Create blank files for each lesson (main with provider and backend) no resources

**Comment by chitopunk** [comment]
@charlycastro @dancortes94  are we doing to do this at the end?

**Comment by chitopunk** [comment]
this was already fixed

**Comment by estebancrw** [comment]
I think this is already done - can we close this issue? @chitopunk @charlycastro @dancortes94
